project/apps/shop/urls.py
from django.urls import path
from django.views.generic.base import TemplateView

from . import views

app_name = 'shop'


urlpatterns = [
    path('order/', views.OrderCreateView.as_view(), name='order'),
    path('order-pay/<int:order_id>', views.OrderPay.as_view(), name='order-pay'),
    path('payment/', TemplateView.as_view(template_name='sber_acquiring/successful_payment.html'), name='successful_pay'),
    #path('not_payment/', TemplateView.as_view(template_name='sber_acquiring/unsuccessful_payment.html'),
    #    name='unsuccessful_pay')
    path('not_payment/', views.NotPaymentView.as_view(), name='unsuccessful_pay')
]

project/system/urls.py
import debug_toolbar
from apps.domains.views import ChangeDomain
from apps.pages.views import IndexView
from django.conf import settings
from django.conf.urls.static import static
from django.contrib import admin
from django.urls import path, include
from django.views.generic import RedirectView
from django.views.generic import TemplateView
from apps.configuration.models import Settings
from apps.configuration.views import autotestHandler
from django.contrib.sitemaps.views import sitemap
from django.contrib.sitemaps import Sitemap
from apps.domains.middleware import get_request
from apps.catalog import models as catalog_models
from apps.pages import models as pages_models
from django.shortcuts import reverse

class ProductsSitemap(Sitemap):

    def items(self):
        return catalog_models.Product.objects.active()

class CategorySitemap(Sitemap):

    def items(self):
        domain = get_request().domain
        return catalog_models.Catalog.objects.filter(is_active=True, domain__exact=domain)

class PageSitemap(Sitemap):

    def items(self):
        return pages_models.Page.objects.activated()

sitemaps = {
    'products': ProductsSitemap,
    'categories': CategorySitemap,
    'pages': PageSitemap,
}

class Favicon(RedirectView):

    def get_redirect_url(self, *args, **kwargs):
        return Settings.get_settings().favicon.url


urlpatterns = static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT) + [
    path("sitemap.xml", sitemap, {'sitemaps': sitemaps}, name='django.contrib.sitemaps.views.sitemap'),
    path('__debug__/', include(debug_toolbar.urls)),
    path('ckeditor/', include('ckeditor_uploader.urls')),
    path('jet/', include('jet.urls', 'jet')),
    path('jet/dashboard/', include('jet.dashboard.urls',
                                   'jet-dashboard')),
    path("autotest/start/", autotestHandler),
    path("admin/", admin.site.urls),
    path('favicon.ico', Favicon.as_view()),
    path("", include("apps.seo.urls", namespace='seo')),
    path("", include('social_django.urls', namespace='social')),
    path("", IndexView.as_view(), name='index'),
    path('change/', ChangeDomain.as_view(), name='change_domain'),
    path('feedback/api/', include('apps.feedback.urls')),
    path("", include('apps.reviews.urls')),
    path("", include("apps.catalog.urls")),
    path("", include("apps.shop.urls", namespace='shop')),
    path("", include("apps.exchange1c.urls")),
    path("apiship/", include("apps.apiship.urls", namespace='apiship')),
    path("cart/", include("apps.cart.urls", namespace='cart')),
    path("compare/", include("apps.compare.urls", namespace='compare')),
    path("komtet/", include("apps.komtet.urls", namespace='komtet')),
    path("sber/", include("apps.sber_acquiring.urls", namespace='sber')),
    path("users/", include("apps.users.urls")),
    path("wishlist/", include("apps.wishlist.urls", namespace='wishlist')),
    path("", include("apps.pages.urls", namespace='pages')),
]

project/apps/shop/models/endpoints.py
from django import forms
from django.db import models
from django.db.models import Q
from django.apps import apps

from apps.catalog.models import Brand


class EndPoint(models.Model):
    store = models.ForeignKey('stores.Store', verbose_name="Магазин", blank=True, null=True, on_delete=models.CASCADE)
    domain = models.ForeignKey('domains.Domain', verbose_name="Домены", blank=True, null=True, on_delete=models.CASCADE)
    condition = models.TextField('Условие',
                                 help_text="В каждой строке применяется И, на каждую новую строку ИЛИ\n"
                                           "& - разделитель атрибутов,\n"
                                           "[store] - переменная выбранного магазина\n"
                                           "[domain] - переменная выбранного города\n")
    slug = models.CharField('Слаг', max_length=15, help_text='Строка между 1c_exchange и .py', unique=True)

    class Meta:
        ordering = ['slug']
        verbose_name = 'Эндпоинт'
        verbose_name_plural = 'Эндопоинты'

    def __str__(self):
        return self.slug

    def clean(self):
        filters = self.get_filters()
        if filters:
            Order = apps.get_model('shop', 'Order')
            try:
                Order.objects.filter(filters).count()
            except Exception as error:
                raise forms.ValidationError({'condition': f'Поле заполнено не верно! {error}'})
        else:
            raise forms.ValidationError({'condition': 'Поле заполнено не верно!'})

    def filter(self, qs):
        print("filters", self.get_filters())
        qs = qs.filter(self.get_filters())
        return qs

    def get_variable(self, value):
        value = value.replace('\r', '')
        if value == '[store]':
            return self.store
        if value == '[domain]':
            return self.domain
        return value

    def get_filters(self):
        q = Q()
        try:
            lines = self.condition.split('\n')
            for line in lines:
                attrs = line.split('&')
                q_and = Q()
                for attr in attrs:
                    key, value = attr.split('=')
                    value = self.get_variable(value)
                    q_and &= Q(**{f'{key}': value})
                q |= q_and
            if self.store.title == 'ул. Фучика, 9':
                q &= ~Q(items__product__brand__title='Гефест')
        except Exception:
            pass
        return q

project/apps/shop/forms.py
from django.forms import ModelForm, forms

from .models import Order
from ..domains.middleware import get_request
from django.db.models import Q
from apps.catalog.models import get_contractor


class OrderForm(ModelForm):

    def __init__(self, *args, **kwargs):
        super(OrderForm, self).__init__(*args, **kwargs)
        request = get_request()
        domain = request.domain
        contractor = 'price' + get_contractor(request)

        if self.fields.get('delivery'):
            self.fields['delivery'].queryset = self.fields['delivery'].queryset\
                .filter(domain__exact=domain)\
                .filter(Q(type_price__title__exact=contractor) | Q(type_price__isnull=True))

        if self.fields.get('payment'):
            self.fields['payment'].queryset = self.fields['payment'].queryset\
                .filter(domain__exact=domain)\
                .filter(Q(type_price__title__exact=contractor) | Q(type_price__isnull=True))

    class Meta:
        model = Order
        fields = ['name', 'phone', 'email', 'delivery', 'store', 'payment', 'comment', 'address']

    def clean(self):
        data = self.cleaned_data
        store = data.get('store')

        print("Cleaned data", data)

        if delivery := data.get('delivery'):
            if delivery.stores.exists():
                if store:
                    store = delivery.stores.filter(id=store.id).first()
                if not store:
                    raise forms.ValidationError({'store': 'Укажите значение из списка'})
                else:
                    data['address'] = ''
                # else:
                #     data['address'] = f'{store.domain.name}, {store.address}'
            else:
                if not data.get('address'):
                    raise forms.ValidationError({'address': 'Укажите адрес'})
                else:
                    data['store'] = None
        return data

project/apps/shop/views.py
import traceback
from django.contrib.sites.shortcuts import get_current_site
from django.core.mail import EmailMessage
from django.db import transaction
from django.http import JsonResponse, Http404, HttpResponseRedirect
from django.template.loader import get_template, render_to_string
from django.urls import reverse_lazy
from django.utils.encoding import force_bytes, force_text
from django.utils.http import urlsafe_base64_encode, urlsafe_base64_decode
from django.views.generic import FormView, RedirectView
from django.shortcuts import redirect
import json
import webbrowser


from django.views.generic import TemplateView
from .forms import OrderForm
from apps.users.tokens import account_activation_token
from ..commons.mixins import ContextPageMixin
from ..configuration.models import Settings
from ..pages.models import Page
from apps.feedback.models import Mail
from apps.feedback.mailer import Mailer
from apps.cart.models import Cart, CartItem, get_cart
from apps.cart.models.base import get_gefest
from apps.sber_acquiring.models import BankOrder
from apps.users.models import Account
from apps.shop.models import Order
from apps.catalog.models import Brand


class OrderCreateView(ContextPageMixin, FormView):
    """
    Оформление заказа
    """
    form_class = OrderForm
    template_name = 'shop/order.html'
    success_url = reverse_lazy('personal-orders')
    page = Page.TemplateChoice.ORDER

    def dispatch(self, request, *args, **kwargs):
        cart = get_cart(self.request)
        if not cart.exists() and not self.request.GET.get('success'):
            return redirect('index')
        return super(OrderCreateView, self).dispatch(request, *args, **kwargs)

    def get_initial(self):
        initial = super(OrderCreateView, self).get_initial()
        if self.request.user.is_authenticated:
            initial['name'] = self.request.user.name
            initial['phone'] = self.request.user.phone
            initial['email'] = self.request.user.email
        return initial

    def form_invalid(self, form):
        return JsonResponse({'errors': form.errors, 'success': False})

    @staticmethod
    def get_success(**kwargs):
        settings = Settings.get_settings()
        template = 'shop/order_empty.html'
        return get_template(template).render({'settings': settings, **kwargs})

    def get_context_data(self, **kwargs):
        context = super(OrderCreateView, self).get_context_data(**kwargs)
        if self.request.GET.get('success'):
            order = self.request.GET.get('order')
            context['template'] = self.get_success(id=order)
        return context

    def get_receivers(self, cart):
        result_receivers = []
        cart_receivers = []
        
        #if self.request.domain.domain == 'spb.rupechi.ru':
        if get_gefest(get_cart(self.request)):
            result_receivers.append('tlcub@rupechi.ru')
        else:
            result_receivers.append('kubatura@rupechi.ru')

        #try:
        #    cart_items = CartItem.objects.filter(cart__id=cart.id)
        #    list_cart_receivers = [list(item.product.category.get_ancestors(include_self=True)) for item in cart_items]
        #    for cart_receiver in list_cart_receivers:
        #        cart_receivers.extend(cart_receiver)
        #    cart_receivers = [list(item.receivers.all()) for item in cart_receiver]
        #except:
        #    cart_receivers = [item.product.category.receivers.all() for item in cart.items()]

        #for cart_item in cart_receivers:
        #    result_receivers.extend(cart_item)

        return result_receivers

    @transaction.atomic
    def form_valid(self, form):
        # получение корзины
        cart = get_cart(self.request)
        cart_receivers = self.get_receivers(cart)
        user = self.request.user
        if not user.is_authenticated:
            user, created = Account.objects.get_or_create(email=form.cleaned_data.get('email'),
                                                          defaults={
                                                              'name': form.cleaned_data.get('name'),
                                                              'phone': form.cleaned_data.get('phone')
                                                          })
            if created:
                password = Account.objects.make_random_password()
                user.set_password(password)
                current_site = get_current_site(self.request)
                mail_subject = 'Активация учетной записи'
                message = render_to_string('users/mail/user_confirm.html', {
                    'user': user,
                    'domain': current_site.domain,
                    'uid': urlsafe_base64_encode(force_bytes(user.pk)),
                    'token': account_activation_token.make_token(user),
                    'request': self.request,
                    'password': password,
                })
                email = EmailMessage(
                    mail_subject, message, to=[form.cleaned_data.get('email')]
                )
                email.send()
                Account.auth(self.request, user)
                admin_mail = Mail.objects.filter(type=Mail.TypeChoice.REGISTER, domains__exact=self.request.domain).first()
                emails_admin = list(admin_mail.recipients.values_list('email', flat=True))
                mail_subject_admin = 'Регистрация нового пользователя'
                message_admin = render_to_string('feedback/register/message.html', {
                    'mail': email,
                    'request': self.request,
                    'user': user,
                })

                Mailer.send(
                    subject=mail_subject_admin,
                    html=message_admin, to=emails_admin
                )

            user.save()
            
        order = form.save(commit=False)
        order.user = user
        order.total = cart.total
        order.total_original = cart.total_without_discount
        order.city = self.request.domain.name
        order.domain = self.request.domain
        order.save()

        # добавление элементов заказа
        order.create_items(cart)
        order.send_notifications()
        order.send_admin_notifications(cart_receivers)

        # очистка корзины
        cart.clear()
        if str(form.cleaned_data.get('payment')) == 'На сайте картой Visa, Mastercard или Мир':
            try:
                order.status = Order.AWAITING
                order.save(update_fields=['status'])
                bank_order = BankOrder.register_order(order, self.request.domain.domain)
                return JsonResponse({
                    'success': True,
                    'redirect': True,
                    'redirect_url': bank_order.formUrl,
                    'template': self.get_success(id=order.id, pay_url=bank_order.formUrl, payment=True),
                    'order': {'id': order.id}
                })
            except Exception as e:
                print(f'=====DEBUG SBER PAYMENT ERROR {e}')
                raise
            
        return JsonResponse({
            'success': True,
            'redirect': False,
            'template': self.get_success(id=order.id, payment=False),
            'order': {
                'id': order.id,
            }
        })


class OrderPay(RedirectView):

    def get_redirect_url(self, *args, **kwargs):
        order = Order.objects.get(id=kwargs.get('order_id'))
        bank_order = BankOrder.register_order(order, self.request.domain.domain)
        try:
            print("Bank url", bank_order.formUrl)
            return bank_order.formUrl
        except:
            print(f'=====ERROR BANK ORDER {bank_order.__dict__}')
            return '/'


class NotPaymentView(TemplateView):
    template_name = "sber_acquiring/unsuccessful_payment.html"

    def get_context_data(self, **kwargs):

        context = super().get_context_data(**kwargs)

        try:
            context["id"] = Order.objects.get(bank_data__bank_id=self.request.GET.get("orderId")).pk
        except:
            traceback.print_exc()

        print(context)

        return context

project/apps/shop/templates/shop/order.html
{% extends 'base.html' %}

{% load static catalog %}

{% block header_extra %}
    <link rel="stylesheet" href="{% static 'css/orderPage.css' %}?v={{ v }}">
{% endblock %}

{% block footer_extra %}
    <script src="{% static 'js/orderPage.bundle.js' %}?v={{ v }}"></script>
{% endblock %}

{% block page_title %}
{% if not template %} {{ block.super }} {% endif %}
{% endblock %}

{% block content %}
    <section class="order-section">
        <div class="section-wrapper">
            {% if template %}
                {{ template }}
            {% else %}
                <form class="order" action="{% url 'shop:order' %}">
                    <div class="order-step">
                        <div class="order-step-header">
                            <span class="order-step-header__counter">1.</span>
                            <span class="order-step-header__text">Контакные данные получателя</span>
                        </div>
                        <div class="order-step-body">
                            <label class="order-step-line">
                                <span class="order-step-line__title">{{ form.name.label }}</span>
                                <input type="text" class="order-step-line__input"
                                       pattern="^[А-Яа-яЁё\s]+$"
                                       {% if form.name.field. %}
                                       
                                       {% endif %}
                                       name="{{ form.name.name }}"
                                       value="{{ form.initial.name }}">
                            </label>
                            <label class="order-step-line">
                                <span class="order-step-line__title">{{ form.phone.label }}</span>
                                <input type="tel" class="order-step-line__input" name="{{ form.phone.name }}"
                                       {% if form.phone.field. %}
                                       
                                       {% endif %}
                                       value="{{ form.initial.phone }}">
                            </label>
                            <label class="order-step-line">
                                <span class="order-step-line__title">{{ form.email.label }}</span>
                                <input type="email" class="order-step-line__input" name="{{ form.email.name }}"
                                       {% if form.email.field. %}
                                       
                                       {% endif %}
                                       value="{{ form.initial.email }}">
                            </label>
                        </div>
                    </div>
                    <div class="order-step">
                        <div class="order-step-header">
                            <span class="order-step-header__counter">2.</span>
                            <span class="order-step-header__text">Способ доставки</span>
                        </div>
                        <div class="order-step-body">
                            {% for item in form.delivery.field.queryset %}
                                <div class="order-step-radio">
                                    <label class="order-step-radio__wrapper {%if item.selection%}order-step-radio_active{% else %}order-step-radio_not_active{%endif%}">
                                        <input type="radio" name="{{ form.delivery.name }}" value="{{ item.id }}" {% if forloop.first %}checked="checked"{% endif %}>
                                        <span>
                                    <span class="order-step-radio__marker"></span>
                                </span>
                                        <span class="order-step-radio-info">
                                    <span class="order-step-radio__title">{{ item.title }}</span>
                                    <span class="order-step-radio__subtitle" {%if item.selection%}style="background-color: #ffdbae; border-radius: 4px; padding: 5px; color: #000000"{%endif%}>
                                    {{ item.subtitle }}
                                    </span>
                                </span>
                                    </label>
                                    <div class="order-step-radio-body">
                                        {% with item.stores.get_current.all as stores %}
                                            {% if stores %}
                                                <div class="my-select">
                                                    <div class="my-select-header">
                                                        <input type="hidden" name="{{ form.store.name }}"
                                                               class="my-select-header__selected">
                                                        <span class="my-select-header__option"></span>
                                                        <svg role="img" class="my-select-header__svg">
                                                            <use href="/static/images/sprite.svg#dropdown"></use>
                                                        </svg>
                                                    </div>
                                                    <div class="my-select-dropdown">
                                                        <div class="my-select-dropdown__wrap" data-simplebar>
                                                            {% for store in stores %}
                                                                <a href="#"
                                                                   class="my-select-dropdown__option"
                                                                   data-select="{{ store.id }}">{{ store.title }}</a>
                                                            {% endfor %}
                                                        </div>
                                                    </div>
                                                </div>
                                            {% else %}
                                                <label>
                                                    <input type="text" name="{{ form.address.name }}"
                                                           {% if forloop.first %}  {% endif %}
                                                           placeholder="Укажите точный адрес доставки">
                                                </label>
                                            {% endif %}
                                        {% endwith %}
                                    </div>
                                </div>
                            {% endfor %}
                            <label class="order-step-body-comment">
                                <span class="order-step-body-comment__text">{{ form.comment.label }}</span>
                                <textarea name="{{ form.comment.name }}"></textarea>
                            </label>
                        </div>
                    </div>

                    <div class="order-step">
                        <div class="order-step-header">
                            <span class="order-step-header__counter">3.</span>
                            <span class="order-step-header__text">Способ оплаты</span>
                        </div>
                        <div class="order-step-body">
                            {% for item in form.payment.field.queryset %}
                                <div class="order-step-radio center {%if item.title == 'Наличными или по карте при получении заказа.'%}order-step-radio__pay{%endif%}">
                                    <label class="order-step-radio__wrapper">
                                        <input type="radio" name="payment" value="{{ item.id }}" {% if forloop.first %}checked="checked"{% endif %}>
                                        <span>
                                    <span class="order-step-radio__marker"></span>
                                </span>
                                        <span class="order-step-radio-info">
                                    <span class="order-step-radio__title">{{ item.title }}</span>
                                </span>
                                    </label>
                                </div>
                            {% endfor %}
                        </div>
                    </div>
                    <div class="order-step">
                        <div class="order-step-header">
                            <span class="order-step-header__text">Состав заказа</span>
                        </div>
                        <div class="order-step-body">
                            <div class="order-cart">
                                {% for item in cart.items %}
                                    <a href="{{ item.product.parent.get_absolute_url|default:item.product.get_absolute_url }}"
                                       class="order-cart-item" data-title="{{ item.product.title }}" data-id="{{ item.product.id }}"
                                       data-price="{{ item.product.get_storage_info.price }}" data-brand="{{ item.product.brand }}"
                                       data-category="{{ item.product.category }}" data-quantity="{{ item.quantity }}"
                                    >
                                        {% if item.product.parent.image or item.product.image %}
                                            <div class="order-cart-item-image">
                                                {% if item.product.parent.image %}
                                                    {{ item.product.parent.get_template_picture }}
                                                {% elif item.product.image %}
                                                    {{ item.product.get_template_picture }}
                                                {% endif %}
                                            </div>
                                        {% endif %}
                                        <div class="order-cart-item__title">{{ item.product.title }}</div>
                                        <div class="order-cart-item__quantity">{{ item.quantity }} шт.</div>
                                        <div class="order-cart-item__total">{{ item.total|convert_price }}</div>
                                    </a>
                                {% endfor %}
                            </div>
                            <div class="order-total">
                                <div class="order-total__wrapper">
                                    <div class="order-total-info">
                                        <div class="order-total-info__text">Всего к оплате:</div>
                                        <div class="order-total-info__total">{{ cart.total|convert_price }}</div>
                                    </div>
                                    {% if personal_page %}
                                        <div class="order-total-info__message">
                                            Нажимая на кнопку «Подтвердить заказ», я даю
                                            <a href="{{ personal_page.get_absolute_url }}"  target="_blank">
                                                согласие на обработку персональных данных</a>
                                        </div>
                                    {% endif %}
                                </div>
                                <button class="btn btn-primary" type="submit">
                                    <span class="btn__text">Подтвердить заказ</span>
                                </button>
                            </div>
                        </div>
                    </div>
                </form>
            {% endif %}
        </div>
    </section>
{% endblock %}

project/apps/shop/templates/shop/order_empty.html
{% load static %}
<div class="order-empty">
    <svg class="order-empty__svg" role="img">
        <use href="{% static 'images/sprite.svg' %}#success"></use>
    </svg>
    <div class="order-empty__title">Спасибо за заявку! <span> №{{ id }}</span></div>
    <div class="order-empty__subtitle">Менеджер свяжется с Вами в ближайшее время.</div>
    <div class="order-empty__buttons">
        <a href="/" class="btn btn-primary">
            <svg role="img">
                <use href="{% static 'images/sprite.svg' %}#dropdown"></use>
            </svg>
            <span class="btn__text">Вернуться в магазин</span>
        </a>
        <a href="{{ settings.vkontakte|default:'#' }}" class="btn__vk">
            <svg role="img">
                <use href="{% static 'images/sprite.svg' %}#vk"></use>
            </svg>
        </a>
    </div>
</div>

project/apps/shop/templates/shop/order_not_payment.html
{% extends 'base.html' %}
{% load static %}

{% load static catalog %}

{% block header_extra %}
    <link rel="stylesheet" href="{% static 'css/orderPage.css' %}?v={{ v }}">
{% endblock %}

{% block meta_title %}
Оплата заказа
{% endblock %}

{% block footer_extra %}
    <script src="{% static 'js/orderPage.bundle.js' %}?v={{ v }}"></script>
{% endblock %}

{% block page_title %}
{% if not template %} {{ block.super }} {% endif %}
{% endblock %}

{% block content %}
<div class="order-empty">
    <svg class="order-empty__svg" role="img">
        <use href="{% static 'images/sprite.svg' %}#success"></use>
    </svg>
    <div class="order-empty__title" style="font-size: 30px">Оплата заказа не удалась</div>
    <div class="order-empty__subtitle">Менеджер свяжется с Вами в ближайшее время.</div>
    <div class="order-empty__buttons">
        <a href="/" class="btn btn-primary">
            <span class="btn__text">На главную</span>
        </a>
        <a href="{{ settings.vkontakte|default:'#' }}" class="btn__vk">
            <svg role="img">
                <use href="{% static 'images/sprite.svg' %}#vk"></use>
            </svg>
        </a>
    </div>
</div>
{% endblock %}

project/apps/shop/templates/shop/order_payment.html
{% load static %}
<div class="order-empty">
    <svg class="order-empty__svg" role="img">
        <use href="{% static 'images/sprite.svg' %}#success"></use>
    </svg>
    <div class="order-empty__title">Спасибо за заявку! <span> №{{ id }}</span></div>
    <div class="order-empty__subtitle">Менеджер свяжется с Вами в ближайшее время.</div>
    <div class="order-empty__subtitle">Для оплаты заказа нажмите на кнопку "Оплатить заказ"</div>
    <div class="order-empty__buttons">
        <a href="{{ pay_url }}" class="btn btn-primary">
            <span class="btn__text">Оплатить заказ</span>
        </a>
        <a href="{{ settings.vkontakte|default:'#' }}" class="btn__vk">
            <svg role="img">
                <use href="{% static 'images/sprite.svg' %}#vk"></use>
            </svg>
        </a>
    </div>
</div>

project/apps/shop/templates/shop/orders_changelist.html
{% extends 'admin/change_list.html' %}

{% block object-tools %}
    <div>
        <form action="export-order/" method="POST">
            {% csrf_token %}
                <input type="submit" value="Экспортировать в Excel"></button>
        </form>
    </div>
    <br />
    {{ block.super }}
{% endblock %}