project/apps/feedback/urls.py
from django.urls import path
from apps.feedback.views import GiveCoupon, CalcMounting, SubscribeView, CoopView, OneClickView, CheaperView, InStockView

app_name = 'feedback'

urlpatterns = [
    path('coupon/', GiveCoupon.as_view(), name='coupon'),
    path('mounting/', CalcMounting.as_view(), name='mounting'),
    path('subscribe/', SubscribeView.as_view(), name='subscribe'),
    path('coop/', CoopView.as_view(), name='coop'),
    path('oneclick/', OneClickView.as_view(), name='oneclick'),
    path('cheaper/', CheaperView.as_view(), name='cheaper'),
    path('in-stock/', InStockView.as_view(), name='in_stock')
]

project/system/urls.py
import debug_toolbar
from apps.domains.views import ChangeDomain
from apps.pages.views import IndexView
from django.conf import settings
from django.conf.urls.static import static
from django.contrib import admin
from django.urls import path, include
from django.views.generic import RedirectView
from django.views.generic import TemplateView
from apps.configuration.models import Settings
from apps.configuration.views import autotestHandler
from django.contrib.sitemaps.views import sitemap
from django.contrib.sitemaps import Sitemap
from apps.domains.middleware import get_request
from apps.catalog import models as catalog_models
from apps.pages import models as pages_models
from django.shortcuts import reverse

class ProductsSitemap(Sitemap):

    def items(self):
        return catalog_models.Product.objects.active()

class CategorySitemap(Sitemap):

    def items(self):
        domain = get_request().domain
        return catalog_models.Catalog.objects.filter(is_active=True, domain__exact=domain)

class PageSitemap(Sitemap):

    def items(self):
        return pages_models.Page.objects.activated()

sitemaps = {
    'products': ProductsSitemap,
    'categories': CategorySitemap,
    'pages': PageSitemap,
}

class Favicon(RedirectView):

    def get_redirect_url(self, *args, **kwargs):
        return Settings.get_settings().favicon.url


urlpatterns = static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT) + [
    path("sitemap.xml", sitemap, {'sitemaps': sitemaps}, name='django.contrib.sitemaps.views.sitemap'),
    path('__debug__/', include(debug_toolbar.urls)),
    path('ckeditor/', include('ckeditor_uploader.urls')),
    path('jet/', include('jet.urls', 'jet')),
    path('jet/dashboard/', include('jet.dashboard.urls',
                                   'jet-dashboard')),
    path("autotest/start/", autotestHandler),
    path("admin/", admin.site.urls),
    path('favicon.ico', Favicon.as_view()),
    path("", include("apps.seo.urls", namespace='seo')),
    path("", include('social_django.urls', namespace='social')),
    path("", IndexView.as_view(), name='index'),
    path('change/', ChangeDomain.as_view(), name='change_domain'),
    path('feedback/api/', include('apps.feedback.urls')),
    path("", include('apps.reviews.urls')),
    path("", include("apps.catalog.urls")),
    path("", include("apps.shop.urls", namespace='shop')),
    path("", include("apps.exchange1c.urls")),
    path("apiship/", include("apps.apiship.urls", namespace='apiship')),
    path("cart/", include("apps.cart.urls", namespace='cart')),
    path("compare/", include("apps.compare.urls", namespace='compare')),
    path("komtet/", include("apps.komtet.urls", namespace='komtet')),
    path("sber/", include("apps.sber_acquiring.urls", namespace='sber')),
    path("users/", include("apps.users.urls")),
    path("wishlist/", include("apps.wishlist.urls", namespace='wishlist')),
    path("", include("apps.pages.urls", namespace='pages')),
]

project/apps/catalog/models/product.py
import decimal
import itertools
import os

from apps.commons.models import ImageModel, WithBreadcrumbs, FullSlugMixin
from apps.domains.models import Domain
from apps.domains.middleware import get_request
from apps.seo.models import SeoBase
from apps.seo.templatetags.seo import Seo

from ckeditor_uploader.fields import RichTextUploadingField
from django.apps import apps
from django.contrib.postgres.indexes import GinIndex
from django.contrib.postgres.search import SearchVectorField, SearchVector
from django.core.validators import MinValueValidator, MaxValueValidator
from django.db import models
from django.db.models import When, Case, Sum, Count, Avg, F, Min, Q, QuerySet
from django.urls import reverse
from django.utils.safestring import mark_safe
from django.core.cache import cache
from mptt.models import MPTTModel, TreeForeignKey

from . import get_contractor
from ..managers import ProductManager
from ...configuration.models import Settings
from .category import *

from django.db.models.signals import post_save
from django.dispatch import receiver
import math

def _get_field(number=None, required=True, old=''):
    data = {}
    name = old + 'Розничная цена'
    if number:
        name = old + 'Цена контрагента №' + str(number)
    if required:
        data['blank'] = True
        data['null'] = True
    return models.DecimalField(name, decimal_places=2, max_digits=10, **data)


def get_old_price_field(number=None, required=True):
    return _get_field(number, required, 'Старая ')


def get_price_field(number=None, required=True):
    return _get_field(number, required)


CONTRACTORS_COUNT = 3

# Миграции нормально не работают, связано это с неправильной миграцией некоторых моделей, где создавались/удалялись поля
# Можно попробовать удалить список миграций, тогда, по-идее, миграции должны заработать
class Product(MPTTModel, FullSlugMixin, ImageModel, WithBreadcrumbs, SeoBase):
    # managers
    objects = ProductManager()

    class Meta:
        verbose_name = 'Товар'
        verbose_name_plural = 'Товары'
        ordering = ('title',)
        indexes = [GinIndex(fields=['search_vector'])]

    ONLY = ('title', 'slug', 'code', 'price', 'old_price', 'stock')

    parent = TreeForeignKey('self', verbose_name='Родительский товар',
                            on_delete=models.CASCADE, blank=True, null=True,
                            related_name='variations')
    is_active = models.BooleanField(
        verbose_name='Активен', default=True, db_index=True)
    is_discount = models.ManyToManyField(Domain, verbose_name='Не применять скидку 5% на доменах',
                                         related_name='product_discount', blank=True, null=True)
    is_import_active = models.BooleanField('В выгрузке', default=True)
    category = models.ForeignKey(
        'catalog.Category', verbose_name='Категория', related_name='products',
        on_delete=models.CASCADE, blank=True, null=True)
    brand = models.ForeignKey(
        'catalog.Brand', related_name='brand_products', on_delete=models.SET_NULL,
        blank=True, null=True)
    # info
    title = models.CharField(
        verbose_name='Название', max_length=127, db_index=True)
    slug = models.SlugField(verbose_name='Слаг', max_length=255, db_index=True)
    code = models.CharField(
        verbose_name='Артикул', blank=True, null=True, max_length=63)
    description = RichTextUploadingField(
        verbose_name='Описание', blank=True, default='')

    last_description = models.TextField(
		verbose_name='Описание', blank=True, default='')

    stock = models.PositiveIntegerField(
        verbose_name='Остаток на складе', default=0)
    attributes = models.ManyToManyField(
        'ProductAttribute', verbose_name='Атрибуты',
        through='AttributeProducValue')
    related_products = models.ManyToManyField(
        'self', verbose_name='Сопутствующие товары', blank=True,
        symmetrical=False)
    views = models.PositiveIntegerField('Просмотры', default=0, editable=False)

    # shipping parameters
    weight = models.PositiveIntegerField(verbose_name="Масса", default=0)
    width = models.PositiveIntegerField(verbose_name="Ширина", default=0)
    height = models.PositiveIntegerField(verbose_name="Высота", default=0)
    length = models.PositiveIntegerField(verbose_name="Длина", default=0)
    # const
    hit = models.BooleanField('Хит', default=False)
    new = models.BooleanField('Новинка', default=False)
    offer = models.BooleanField('Акция', default=False)
    top_hit = models.BooleanField('Топ продаж', help_text='Блок на главной', default=False)
    # import
    id_1c = models.UUIDField(
        verbose_name='Идентификатор 1С', blank=True, null=True, unique=True,
        help_text='Заполняется автоматически')
    # search
    search_vector = SearchVectorField(null=True)
    # dates
    created_at = models.DateTimeField(
        verbose_name='Дата создания', auto_now_add=True)
    updated_at = models.DateTimeField(
        verbose_name='Дата последнего обновления', auto_now=True)
    keywords = models.CharField('Ключевые слова', max_length=125, default="", blank=True)

    VIEWED_SESSION_ID = 'viewed_products'

    lastStockQuantityBoolean = models.BooleanField(default=False)

    def replace_selectionTags(self):
        desc = self.description
        print(desc)

    def __str__(self):
        return self.title

    def save(self, *args, **kwargs):
        search_vector = (
                SearchVector('title', weight='A')
                + SearchVector('description', weight='B')
        )
        # поисковой вектор можно обновлять только у уже существующих записей бд
        if not self.is_active:
            print(f'=== DEACT DEBUG PRODUCT ID {self.id_1c}')
        if self.pk:
            self.search_vector = search_vector
            return super().save(*args, **kwargs)
        else:
            _ = super().save(*args, **kwargs)
            Product.objects.filter(pk=self.pk).update(
                search_vector=search_vector)
            return _

    def in_stock(self):
        domain = get_request().domain
        return bool(self.quantity_stores.filter(quantity__gt=0, store__domain=domain))

    @staticmethod
    def autocomplete_search_fields():
        """jet admin"""
        return 'title', 'slug'

    def get_absolute_url(self, **kwargs):
        return reverse('product', kwargs={'slug': self.encode_slug()})

    def get_breadcrumbs(self, **kwargs):
        if self.parent:
            breadcrumbs = self.parent.get_breadcrumbs()
            breadcrumbs.append((self.title, self.get_absolute_url()))
        elif self.category:
            breadcrumbs = self.category.get_breadcrumbs()
            breadcrumbs.append((self.title, self.get_absolute_url()))
        else:
            breadcrumbs = super().get_breadcrumbs()
        breadcrumbs[-1] = (breadcrumbs[-1][0], '#')
        return breadcrumbs

    def get_price_line(self, domain=None):
        domain = domain or get_request().domain
        return self.prices.filter(domain=domain).first()

    def clean_description(self, description):
        ReplaceAttr = apps.get_model('catalog.ReplaceAttr')
        for item in ReplaceAttr.objects.iterator():
            slug = item.slug
            if slug in description:
                attr = self.product_attributes.filter(attribute=item.attribute).first()
                if attr:
                    description = description.replace(slug, str(attr.value))
        if self.brand:
            description = description.replace('||brand||', self.brand.__str__())
        description = Seo(context={'object': self}).clean(description)
        description = description.replace('"', "'")
        return description

    def get_quantity_stores(self):
        domain = get_request().domain
        stores = self.quantity_stores.filter(store__domain=domain, store__is_active=True)
        quantity_stores = [{'store': store.store, 'quantity': store.quantity,
                           'price': store.product.get_storage_info()['price']} for store in stores]
        return quantity_stores

    def get_description(self):
        description = self.category.product_description
        if not description:
            description = self.description
        result_description = mark_safe(self.clean_description(description))
        return result_description

    def get_unlink_brand(self):
        return self.category.get_ancestors(include_self=True).filter(unlink_brand=True).exists()

    def get_preview_attrs(self):
        dict_attrs = self.product_attributes.filter(attribute__visible_on_attrs=True) \
                         .filter(attribute__type='dict').order_by('attribute')[:5]
        number_attrs = self.product_attributes.filter(attribute__visible_on_attrs=True) \
                           .filter(attribute__type='number').order_by('attribute')[:5]
        dict_attrs = list(dict_attrs)
        number_attrs = list(number_attrs)
        if self.brand:
            dict_attrs.insert(1, {'attribute': 'Производитель', 'value': self.brand})
        response = dict_attrs + list(number_attrs)
        cache.set(f'{self.id}-get-preview-attrs', response, 10 * 60)
        return response

    def get_storage_info(self, domain=None):
        request = get_request()
        contractor = get_contractor(request)
        is_contractor = False
        contractors = ['1', '2', '3']
        if set(contractor.replace('_', '').split()).intersection(set(contractors)):
            is_contractor = True

        domain = domain or request.domain

        response = {
            'price': 0,
            'quantity': 0,
            'old_price': 0,
        }

        if domain.domain == 'spb.rupechi.ru':
            quantity_vologda = self.quantity_stores.active(domain='www.rupechi.ru').aggregate(
                quantity=Sum('quantity')).get('quantity') or 0
            quantity_spb = self.quantity_stores.active().aggregate(quantity=Sum('quantity')).get('quantity') or 0

project/apps/pages/templates/pages/content/coop.html
<form action="{% url 'feedback:coop' %}" method="POST" class="ajax-form form">
    <div class="form-body">
        <label class="form-line">
            <span class="form-line__title">Имя и фамилия</span>
            <input type="text" class="form-line__input"
                   pattern="^[А-Яа-яЁё\s]+$"
                   name="name">
        </label>
        <label class="form-line">
            <span class="form-line__title">Email</span>
            <input type="email" class="form-line__input" name="email">
        </label>
        <label class="form-line">
            <span class="form-line__title">Телефон</span>
            <input type="tel" class="form-line__input" name="phone">
        </label>
        <label class="form-line">
            <span class="form-line__title">Организация</span>
            <input type="text" class="form-line__input" name="organization">
        </label>
        <label class="form-line">
            <span class="form-line__title">Сообщение</span>
            <textarea name="message"></textarea>
        </label>
    </div>
    <button class="btn btn-primary" type="submit">
        <span class="btn__text">Отправить сообщение</span>
    </button>
    <p class="personal-data-link">
        <span>Нажимая на кнопку, вы соглашаетесь на</span>
        <a href="/soglasie-na-obrabotku-personalnyh-dannyh/" target="_blank">обработку персональных данных.</a>
    </p>
</form>

project/apps/pages/templates/pages/content/files.html
<div class="files">
    <div class="files__wrapper">
        {% for item in object.block.files_items.all %}
        <a class="file" href="{{ item.file.url }}" target="_blank">
            <div class="file-info">
                <span class="name">{{ item.title }}</span>
                <span class="size">
                    <svg role="img">
                        <use href="/static/images/sprite.svg#file"/>
                    </svg>
                    {{ item.extension }} {{ item.get_size }}
                </span>
            </div>
        </a>
        {% endfor %}
    </div>
</div>

project/apps/pages/templates/pages/content/form.html
<div class="mounting-form">
    <div class="mounting-form-info">
        <div class="mounting-form-info__title">Оставьте заявку на расчет стоимости монтажа</div>
        <div class="mounting-form-info__subtitle">
            Мы перезвоним вам, чтобы уточнить детали, и <span class="orange">бесплатно</span> рассчитаем
            стоимость и сроки монтажа.
        </div>
    </div>
    <form class="mounting-form-body ajax-form" method="POST" action="{% url 'feedback:mounting' %}">
        <div class="mounting-form-line">
            <label class="mounting-form-cell">
                <input type="text" name="name" placeholder="Имя" required>
            </label>
            <label class="mounting-form-cell">
                <input type="tel" name="phone" placeholder="Телефон" required>
            </label>
        </div>
        <div class="mounting-form-line">
            <div class="my-select">
                <div class="my-select-header">
                    <input type="hidden" name="device" class="my-select-header__selected" value="Котел">
                    <span class="my-select-header__option">Какой отопительный прибор вам нужно установить?</span>
                    <svg role="img" class="my-select-header__svg">
                        <use href="/static/images/sprite.svg#dropdown"></use>
                    </svg>
                </div>
                <div class="my-select-dropdown">
                    <div class="my-select-dropdown__wrap" data-simplebar>
                        <a href="#"
                           class="my-select-dropdown__option"
                           data-select="Котел">Котел</a>
                        <a href="#"
                           class="my-select-dropdown__option"
                           data-select="Печь">Печь</a>
                        <a href="#"
                           class="my-select-dropdown__option"
                           data-select="Камин">Камин</a>
                        <a href="#"
                           class="my-select-dropdown__option"
                           data-select="Дымоход">Дымоход</a>
                    </div>
                </div>
            </div>
        </div>
        <div class="mounting-form-line submit-line">
            <button class="btn btn-primary btn-green"><span class="btn__text">Получить расчет</span></button>
            {% if personal_page %}
            <div class="mounting-form__help_text">
                Нажимая на кнопку, вы соглашаетесь
                на <a href="{{ personal_page.get_absolute_url }}"  target="_blank">обработку персональных данных</a>
            </div>
            {% endif %}
        </div>
    </form>
</div>

project/apps/pages/templates/pages/content/gallery.html
<div class="gallery row-{{ object.block.in_row|default:2 }}">
    {% for item in object.block.gallery_items.all %}
        <a class="gallery-item" href="{{ item.image.url }}" data-fancybox="group_{{ object.block.id }}">
            <span class="gallery-item__img">
                <img src="{{ item.image.url }}" alt="{{ item.title }}"/>
                <span class="gallery-item__wrapper">
                    <svg role="img">
                        <use href="/static/images/sprite.svg#search"></use>
                    </svg>
                </span>
            </span>
            <span class="gallery-item__sign">{{ item.title }}</span>
        </a>
    {% endfor %}
</div>

project/apps/pages/templates/pages/content/pages.html
<div class="useful">
    {% for item in object.block.get_pages.iterator %}
        <a href="{{ item.page.get_absolute_url }}" class="useful-item">
        <span class="useful-item-image">
            {% if item.page.image %}
                <img src="{{ item.page.image.url }}" alt="{{ item.page }}" class="useful-item-image">
            {% endif %}
        </span>
            <span class="useful-item__text">{{ item.page }}</span>
        </a>
    {% endfor %}
</div>

project/apps/pages/templates/pages/content/products.html
{% for item in object.block.products_items.all %}
    {% include "catalog/product_card.html" with product=item.product %}
{% endfor %}

project/apps/pages/templates/pages/content/quote.html
<div class="quote">
    <p class="quote-text">{{ object.text }}</p>
    {% if object.description %}
    <p class="quote-description">{{ object.description }}</p>
    {% endif %}
</div>

project/apps/pages/templates/pages/content/reviews.html
{% for item in object.block.reviews_items.all %}
    <p>{{ item.name }}</p>
    {% if item.avatar %}
        <img src="{{ item.avatar.url }}">
    {% else %}
        <img src="no_photo.png">
    {% endif %}
    <p>{{ item.text }}</p>
{% endfor %}

project/apps/pages/templates/pages/content/slider.html
{% for slide in object.block.slider_items.all %}
<p>{{ slide.title }}</p>
{{ slide.get_template_picture }}
{% endfor %}

project/apps/pages/templates/pages/content/spoiler.html
<div class="spoiler">
    <div class="spoiler-header {% if object.is_open %}open{% endif %}">
        {{ object.header }}
        <svg role="img">
            <use href="/static/images/sprite.svg#dropdown"></use>
        </svg>
    </div>
    <div class="spoiler-body content-text"
         {% if not object.is_open %}style="display: none;"{% endif %}>
        {{ object.text|safe }}
    </div>
</div>

project/apps/pages/templates/pages/content/text.html
<div class="content-text">{{ object.text|safe }}</div>

project/apps/pages/templates/pages/content/title.html
<div class="content-title">
    <h2>{{ object.title }}</h2>
    <a href="{{ object.btn_link.get_absolute_url }}" class="btn">
        <span class="btn__text">{{ object.btn_title }}</span>
    </a>
</div>

project/apps/pages/templates/pages/content/underline.html
<div class='text_underline'><p>{{ object.text }}</p></div>